# Change these first
owner: benemanuel
repo: status 

sites:
  - name: Geulah
    url: https://geulah.org.il/
  - name: HaTaNaCh
    url: https://hatanach.geulah.org.il/
  - name: ShirHaShirim
    url: https://shirhashirim.org.il/
  - name: Verse test
    url: https://hatanach.geulah.org.il/verse/?cit=Zeph3:8&text
  - name: blog
    url: https://benemanuel.geulah.org.il/feed.xml
  - name: plausible
    url: https://plausible.geulah.org.il/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Systems Status
  introTitle: "Status of sites managed by $OWNER"
  introMessage: "**Upptime** is the open-source uptime monitor powered entirely by GitHub."
  #favicon: https://example.com/favicon.png
  #faviconSvg: https://example.com/logo.svg
  navbar:
    - title: Status
      href: /
  #scripts:
  #  - src: http://plausible.geulah.org.il/js/script.js

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
